### PR TITLE
Replaced mb_convert_encoding with functions from neitanod/forceutf8.

### PR DESCRIPTION
**Pull request by oliverhermanni**
Hi,

I replaced mb_convert_encoding, as it doesn't work sometimes (see also https://github.com/scotteh/php-goose/issues/69). neitanod/forceutf8 does a good job as a replacement. Never had any problems after that.

Hope, this one is also okay. :)

### CODE REVIEW

**Comment by scotteh** [comment]
Do you have an examples of the failures you mentioned?

**Comment by oliverhermanni** [comment]
Yes, please check the URL mentioned in the issue at https://github.com/scotteh/php-goose/issues/69.

It's rare, but happened to me on several URLs I can't find right now. Had this fixed for a while, but never uploaded it.

**Comment by scotteh** [comment]
Thanks for the PR.

I'm a bit wary of adding dependencies if they're not essential. The existing code always attempted to convert even if the encoding wasn't available. Added checks to prevent this which should fix this issue.

Wasn't able to re-create the with the URL mentioned on scotteh/php-goose#69, but that does return a CDN 'browser check' page rather than the actual website contents. It's quite possible a page like this could cause some unusual issues.

If you're still having issues then it might be a matter of using neitanod/forceutf8.

**Comment by oliverhermanni** [comment]
Yes, I understand that. Maybe a try-catch block would be helpful there so it won't return a 500 as it does now.

**Comment by rafwell** [comment]
Maybe duplicate https://github.com/scotteh/php-dom-wrapper/pull/11

**Comment by scotteh** [comment]
Merged #11 which will hopefully fix these issues without an external dependency.

**Pull request closed without merging**
